import BlogImg1 from "./assets/images/blogs/blog1.png";
import BlogImg2 from "./assets/images/blogs/blog2.png";
import BlogImg3 from "./assets/images/blogs/blog3.png";

import ExperienceIcon from "./assets/images/icons/experience.png";
import AudienceIcon from "./assets/images/icons/audience.png";
import TeamIcon from "./assets/images/icons/people.png";
import CustomerIcon from "./assets/images/icons/customer.png";
import StrategeIcon from "./assets/images/icons/stratege.png";

import ServiceIcon1 from "./assets/images/icons/service-1.png";
import ServiceIcon2 from "./assets/images/icons/service-2.png";
import ServiceIcon3 from "./assets/images/icons/service-3.png";
import ServiceIcon4 from "./assets/images/icons/service-4.png";

export interface IBlog {
  image: any;
  title: string;
  desc: string;
  link: string;
}

export const ABOUT = [
  {
    icon: AudienceIcon,
    num: "5M+",
    desc: "Targeted Audience",
    col: 4,
    color: "green",
  },
  {
    icon: ExperienceIcon,
    num: "10+",
    desc: "Years of Experience",
    col: 4,
    color: "orange",
  },
  { icon: TeamIcon, num: "15+", desc: "Team Experts", col: 4, color: "pink" },
  {
    icon: CustomerIcon,
    num: "24/7",
    desc: "Post Purchase Customer Service and Consultancy",
    col: 6,
    color: "yellow",
  },
  {
    icon: StrategeIcon,
    num: "%900+",
    desc: "Best ROI Marketing Strategies",
    col: 6,
    color: "green",
  },
];

export const SELLERS = [
  {
    icon: ServiceIcon1,
    title: "Mega Influencers",
    desc: "If you are aiming for the best return on investment in order to sell out your collection, look no further! With our Mega influencers from various social media platforms, you are able to reach out to more than 5 million audiences in weeks.",
  },
  {
    icon: ServiceIcon2,
    title: "Instagram Celebrities",
    desc: "Get the most appropriate return with the most suitable planning for your budget with the Instagram celebrities that carefully selected by giving priority to their high engagement rates.",
  },
  {
    icon: ServiceIcon3,
    title: "YouTubers",
    desc: "The most convenient way to convey the vision of your project to the audience is with longer marketing videos by YouTubers, according to the statistics.",
  },
  {
    icon: ServiceIcon4,
    title: "Twitter ",
    desc: "Get on the radar of big collectors and investors with our best strategies run by Twitter Influencers.",
  },
];

export const SERVICES = [
  { label: "Instagram", value: "instagram" },
  { label: "Twitter", value: "twitter" },
  { label: "YouTube", value: "youtube" },
  { label: "Tiktok", value: "tiktok" },
];

export const HEADER_MENUS = [
  { menu: "Services", scrollLink: "", link: "/services" },
  { menu: "Clients", scrollLink: "customers", link: "" },
  { menu: "Testimonials", scrollLink: "testimonials", link: "" },
  { menu: "Blogs", scrollLink: "", link: "/blogs" },
  { menu: "About Us", scrollLink: "", link: "/aboutus" },
  { menu: "Become NFT & Crypto Influencer", scrollLink: "", link: "" },
];

export const BUDGETS = [
  { value: "$1000 - $4999", label: "$1000 - $4999" },
  { value: "$5000 - $9999", label: "$5000 - $9999" },
  { value: "$10.000 - $49.999", label: "$10.000 - $49.999" },
  { value: "$50.000 - $99.999", label: "$50.000 - $99.999" },
  { value: "$100.000 - $999.999", label: "$100.000 - $999.999" },
  { value: "$1M+", label: "$1M+" },
];

export const BLOGS: IBlog[] = [
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
];
