import BlogImg1 from "./assets/images/blogs/blog1.png";
import BlogImg2 from "./assets/images/blogs/blog2.png";
import BlogImg3 from "./assets/images/blogs/blog3.png";

export interface IBlog {
  image: any;
  title: string;
  desc: string;
  link: string;
}

export const SERVICES = [
  { label: "Tiktok", value: "tiktok" },
  { label: "Instagram", value: "instagram" },
  { label: "YouTube", value: "youtube" },
  { label: "Twitter", value: "twitter" },
];

export const HEADER_MENUS = [
  { menu: "Services", scrollLink: "", link: "/services" },
  { menu: "Clients", scrollLink: "customers", link: "" },
  { menu: "Testimonials", scrollLink: "testimonials", link: "" },
  { menu: "Blogs", scrollLink: "", link: "/blogs" },
  { menu: "About Us", scrollLink: "", link: "/aboutus" },
  { menu: "Become NFT & Crypto Influencer", scrollLink: "", link: "" },
];

export const BUDGETS = [
  { value: "$1000 - $4999", label: "$1000 - $4999" },
  { value: "$5000 - $9999", label: "$5000 - $9999" },
  { value: "$10.000 - $49.999", label: "$10.000 - $49.999" },
  { value: "$50.000 - $99.999", label: "$50.000 - $99.999" },
  { value: "$100.000 - $999.999", label: "$100.000 - $999.999" },
  { value: "$1M+", label: "$1M+" },
];

export const BLOGS: IBlog[] = [
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg1,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg2,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
  {
    image: BlogImg3,
    title: "Business with Bitcoin",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
    link: "",
  },
];
